### PR TITLE
Fixing quizzes week1to4

### PR DESCRIPTION
**Pull request by WoahDomino**
Not sure if we want to merge this and cause potential changes to previous modules, but here is a series of changes to KA questions

### CODE REVIEW

**Comment by cashaffer** [comment]
Not sure that this answers your question. But these are the kind of changes that you *can* make without causing harm to the course setup or grades.

**Comment by s-edwards** [comment]
Yeah, except that's incorrect :-). Changing exercise IDs in the HTML files will cause ripple effects, because the KA engine stores the ID of the current exercise in a given summary in the database ... and if those IDs change, it will fail to redisplay the exercise appropriately the next time the student views the module. The KA javascript has code that intends to "gracefully" handle this error, but the author's idea of "graceful" leaves a lot to be desired. The KA just shows a completely blank question area if the ID stored in the database can no longer be found in the question summary, but since you have to "answer" a question to move forward to another question, you're essentially stuck with no way out.

So I think we should wait awhile until we're sure students have completed these modules before merging in these changes, because they could still munge up the works (potentially, not guaranteed).

**Comment by awhicks** [comment]
Yes, I assume that I will have to go into the db again and clear out the current_exercise field for those that will be affected, so I'll definitely want to schedule this for when I have a free few minutes to identify the id numbers and dig up the sql command from before

**Comment by s-edwards** [comment]
If we wait until students are finished with these, then no db updates will be necessary. Hence the delay before merging. These modules are all past, and are really only open for late submissions at this point.

**Pull request closed without merging**
